// registry/theme/generate-css.ts
//
// Build step: TS theme objects -> CSS custom properties. Run with:
//   pnpm theme:css        (-> tsx registry/theme/generate-css.ts)
// Re-run after ANY change to tokens.ts or themes.ts.
//
// These `--viz-*` vars serve the CSS-driven chrome: shadcn primitives and the
// `article/*` components, which DO read CSS and DO react to a `.dark` class.
// Charts do NOT read these — they consume the active theme via the provider.
//
// OUTPUT FILE: `viz-theme.css` (NOT `theme.css`). `theme.css` already exists in
// this folder as the hand-written article-typography theme (`--color-*` vars)
// and must not be clobbered. Import BOTH from your globals:
//   @import "../theme/theme.css";       (article typography — hand-written)
//   @import "../theme/viz-theme.css";   (viz design tokens — GENERATED)
//
// Because both the chart provider (themes.carbon) and the `.dark` block below
// are sourced from the SAME theme object, the page's "dark" chrome and the
// chart's "dark" colors cannot drift apart.

import { writeFileSync } from 'node:fs';
import { themes, Theme } from './themes';

const toVars = (t: Theme): string => `
  --viz-fg: ${t.fg};
  --viz-muted: ${t.muted};
  --viz-grid: ${t.grid};
  --viz-surface: ${t.surface};
  --viz-border: ${t.border};
  --viz-accent: ${t.accent};
  --viz-font-body: ${t.fontBody};
  --viz-font-title: ${t.fontTitle};`;

// :root = the default (editorial) theme. .dark = carbon (app-level dark mode).
// Every theme additionally gets a [data-viz-theme="<name>"] selector so a
// subtree can opt into a specific theme's chrome (used by the demo page).
const perThemeBlocks = Object.values(themes)
  .map((t) => `[data-viz-theme="${t.name}"] {${toVars(t)}\n}`)
  .join('\n');

const css = `/* GENERATED by generate-css.ts — do not hand-edit. Run \`pnpm theme:css\`. */
:root {${toVars(themes.editorial)}
}
.dark {${toVars(themes.carbon)}
}
${perThemeBlocks}
`;

writeFileSync(new URL('./viz-theme.css', import.meta.url), css);
console.log('wrote viz-theme.css');
